workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      vars:
        # Railway backend manzilingiz
        API_BASE_URL: "http://169.58.50.197:8000"
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Build APK (release)
        script: |
          flutter build apk --release \
            --dart-define=API_BASE_URL=$API_BASE_URL
      - name: Build AppBundle (release, Play Store uchun)
        script: |
          flutter build appbundle --release \
            --dart-define=API_BASE_URL=$API_BASE_URL
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - payziyevdiyor@gmail.com
        notify:
          success: true
          failure: true
