name: doc_translator
description: "PDF va DOCX fayllarni original formatini saqlab tarjima qiluvchi mobil ilova."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State management
  flutter_riverpod: ^2.5.0

  # Networking
  dio: ^5.4.0

  # Fayl tanlash / ochish
  file_picker: ^8.0.0
  open_file: ^3.3.0
  path_provider: ^2.1.0

  # Lokal saqlash
  shared_preferences: ^2.2.0

  # UI
  percent_indicator: ^4.2.0

  # Nafis tipografika (sarlavhalar uchun dekorativ shrift)
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
